default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: spell_dev

test:
  <<: *default
  database: spell_test

production:
  <<: *default
  database: spell_prod
